// import for library
import Head from "next/head";

// import for components
import Header from "@/components/Header";
import Forms from "@/components/Form";

const Home = () => {

  return (
    <>
      <Head>
        <title>Static Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Forms />
      </main>
    </>
  );
}
export default Home;